blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/dirkgroenen/evse_load_balancer/discussions
    about: Ask questions and discuss ideas with the community
  - name: Home Assistant Community
    url: https://community.home-assistant.io/
    about: Get help from the broader Home Assistant community
